### ISSUE TITLE
esbuild-loader v 2.20.0 does not interpret @ts-ignore / @ts-expect-error comments

### ISSUE THREAD

**Issue by pushkargupta9807** [privatenumber/esbuild-loader#276]
### Bug description

esbuild-loader v 2.20.0 does not interpret @ts-ignore / @ts-expect-error ts comments. 

Reverting back to v 2.16.0 works. 
I have a line of code before which I put // @ts-ignore, but that does not prevent the error from the next line to be ignored.  

### Reproduction

With v 2.20.0 
1) Have a line of code with ts error
2) put // @ts-ignore before 

Compile and observe that the error is still reported. 

### Node.js package manager

yarn

### Environment

```shell
If required, shall update after clarifying my company policies.
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
This is unlikely to be related because esbuild doesn't typecheck. I'm not sure what you're compiling with, but if it was throwing a type error before, it wasn't esbuild. It also doesn't preserve comments like this.

Additionally, there are hardly any runtime differences between https://github.com/privatenumber/esbuild-loader/compare/v2.16.0...v2.20.0

Happy to reopen once a minimal reproduction is provided.
