### ISSUE TITLE
File '@ljharb/tsconfig' not found.

### ISSUE THREAD

**Issue by zhengxs2018** [privatenumber/esbuild-loader#363]
### Problem

I was using the 4.0.3 version before but since yesterday it has been reporting an error

The code and module that went wrong have been identified through both projects, but I didn't find out whose dependency this error message is from

```
qs -> side-channel -> get-intrinsic -> es-errors
```

<img width="672" alt="image" src="https://github.com/privatenumber/esbuild-loader/assets/7506913/78169631-6dd8-4c17-b0e2-ab2d32750014">

```
jsonwebtoken -> jws -> util
```

<img width="662" alt="image" src="https://github.com/privatenumber/esbuild-loader/assets/7506913/62591f92-7997-4b1e-b66f-99e0ce2393da">

If you use esbuild-loader with the above 2 modules in your project, you get the error

```
Error: File '@ljharb/tsconfig' not found.
    at je (/Users/zhengxs/demo/node_modules/get-tsconfig/dist/index.cjs:3:9102)
    at te (/Users/zhengxs/demo/node_modules/get-tsconfig/dist/index.cjs:3:10066)
    at ie (/Users/zhengxs/demo/node_modules/get-tsconfig/dist/index.cjs:3:10781)
    at Object.$e [as getTsconfig] (/Users/zhengxs/demo/node_modules/get-tsconfig/dist/index.cjs:3:10886)
    at Object.ESBuildLoader (/Users/zhengxs/demo/node_modules/esbuild-loader/dist/index.cjs:65:36)
    at LOADER_EXECUTION (/Users/zhengxs/demo/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/Users/zhengxs/demo/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/Users/zhengxs/demo/node_modules/loader-runner/lib/LoaderRunner.js:251:2)
    at /Users/zhengxs/demo/node_modules/loader-runner/lib/LoaderRunner.js:224:4
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

### Expected behavior

Bundle Success

### Minimal reproduction URL

https://stackblitz.com/edit/node-gcfggk?file=package.json

### Version

v4.0.3

### Node.js version

v16.0.0

### Package manager

yarn

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Your minimal reproduction doesn't show the error

**Comment by zhengxs2018** [comment]
> 您的最小再现不会显示错误

Sorry, I moved the sample code

Now try it again.

<img width="572" alt="image" src="https://github.com/privatenumber/esbuild-loader/assets/7506913/55e366e7-9f24-45da-9aba-d2951a88300f">

**Comment by privatenumber** [comment]
Still see the same error, which is not what you're reporting:
```
Module not found: Error: Can't resolve './err' in '/home/projects/node-tux3fu/src'
resolve './err' in '/home/projects/node-tux3fu/src'
  using description file: /home/projects/node-tux3fu/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/projects/node-tux3fu/package.json (relative path: ./src/err)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/projects/node-tux3fu/src/err doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /home/projects/node-tux3fu/src/err.tsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/projects/node-tux3fu/src/err.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/projects/node-tux3fu/src/err.js doesn't exist
      as directory
        /home/projects/node-tux3fu/src/err doesn't exist

webpack 5.90.3 compiled with 1 error in 297 ms
```

I'm going to close this since it doesn't seem like your bug report is ready.

**Comment by zhengxs2018** [comment]
Maybe I don't know how to use this site. changed to a new URL

https://stackblitz.com/edit/node-gcfggk?file=package.json


<img width="1505" alt="image" src="https://github.com/privatenumber/esbuild-loader/assets/7506913/50d21d00-32d5-44f2-8e67-4ccf006c1c30">

**Comment by privatenumber** [comment]
Seems to be happening because esbuild-loader tries to find the tsconfig.json for every file, but I don't think it should happen for dependencies.

In this case, it's happening because `qs` installs `side-channel`, which comes with this tsconfig file:
https://github.com/ljharb/side-channel/blob/main/tsconfig.json

**Comment by srakesh009** [comment]
I too had faced similar issue. In my project, I am not using typescript but still the same error shown by @zhengxs2018 was coming up. I switched the version of get-tsconfig from 4.7.3 to 4.7.2 which is a dependency by "esbuild-loader" & this resolved the above error for me.

In below URL, I don't see no node package in the entire npm registry is having "@ljharb/tsconfig" package as it dependent package. I am not sure from where in the error stack trace there is reference to @ljharb/tsconfig package.

https://www.npmjs.com/package/@ljharb/tsconfig?activeTab=dependents

**Comment by privatenumber** [comment]
### Why is this happening?
- [ljharb](https://github.com/ljharb) recently updated packages with a `tsconfig.json` that extends `@ljharb/tsconfig`
- esbuild-loader resolving `tsconfig.json` on dependency imports (bug)

In the minimal reproduction provided above, it's happening because of [`set-function-length`](https://unpkg.com/browse/set-function-length@1.2.2/tsconfig.json) & [`hasown`](https://unpkg.com/browse/hasown@2.0.2/tsconfig.json). You can grep your `node_modules` for `@ljharb/tsconfig` to find which packages are causing this.

While these errors started happening as a result of ljharb publishing these `tsconfig.json` files (which may be an oversight since it's a dev concern), the bug is in esbuild-loader resolving tsconfig files in dependencies.

### Solution
The fix should be simple: [resolve tsconfig](https://github.com/privatenumber/esbuild-loader/blob/7b948efbf191ce0b35b92b934b528545dfaefe18/src/loader.ts#L85-L89) conditionally if the real path is not in `node_modules`.

### Next steps
I'm happy to accept & review a PR. It should contain a test for this case (fake dependency fixture with `tsconfig.json`).

Locking thread to direct further conversation to PRs.
