### ISSUE TITLE
Esbuild loader Cannot read enum property

### ISSUE THREAD

**Issue by olegKusov** [privatenumber/esbuild-loader#85]
Can't properly configure webpack with esbuild-loader. I'm getting error in enum. 

```
Cannot read property 'MyProperty' of undefined.

enum MyProperty {
  SomeEnum = 'screen_history',
}

const history = MyProperty.SomeEnum;

```

My webpack config:

```
{
        test: /\.js$/,
        loader: 'esbuild-loader',
        options: {
          target: 'es2015',
        },
      },
      {
        test: /\.jsx$/,
        loader: 'esbuild-loader',
        options: {
          loader: 'jsx',
          target: 'es2015',
        },
      },
      {
        test: /\.tsx$/,
        loader: 'esbuild-loader',
        options: {
          loader: 'tsx',
          target: 'es2015',
          tsconfigRaw: require('./tsconfig.json'),
        },
      },
      {
        test: /\.ts$/,
        loader: 'esbuild-loader',
        options: {
          loader: 'ts',
          target: 'es2015',
          tsconfigRaw: require('./tsconfig.json'),
        },
      },


```

**Comment by privatenumber** [comment]
I added a test-case in https://github.com/privatenumber/esbuild-loader/pull/97/ to demonstrate that TypeScript enums compile fine. Check out the test fixture [here](https://github.com/privatenumber/esbuild-loader/pull/97/files#diff-bf9a1884275e8e90ac81e21b2b968727fad499cc1918ccfa3a50da57d00ea56dR65-R76) for a reference.

It seems your error is about something else since it reads:
> Cannot read property 'MyProperty' of undefined.

So it seems you're trying to read the property `MyProperty` of some other variable.

If you're still running into this, send me a link to a minimal reproduction repo and I can take a look.
