### ISSUE TITLE
Anyhow to remove "comments" in minified js?

### ISSUE THREAD

**Issue by josteph** [privatenumber/esbuild-loader#87]
Using `ESBuildMinifyPlugin`, is there anyway to remove the comments in the minified js file?

For example:
![image](https://user-images.githubusercontent.com/13672022/103356619-d9615b80-4ae3-11eb-86c0-0582ee2f1068.png)

If using terser, we can add easily using `comments: false` in the output options.

**Comment by privatenumber** [comment]
This is by design on [esbuild's end](https://esbuild.github.io/api/#charset):
> And all comments other than license-related comments are stripped out by esbuild anyway.

Can you open an issue [here](https://github.com/evanw/esbuild)?

I think [minification-benchmarks](https://github.com/privatenumber/minification-benchmarks) can also benefit from a more nuanced control over removing comments as other minifiers support it.

**Comment by josteph** [comment]
Thanks for the reference 👍

Edit:
I believe it has been answered here https://github.com/evanw/esbuild/issues/578

**Comment by privatenumber** [comment]
I would still open a feature request about having granular control over whether license comments should be kept. Some authors might be referencing licenses in a separate file instead of the JS code.


Since esbuild preserves `@license` comments, you can try removing it to trick esbuild into thinking it's an ordinary comment.

As an example, you can use [code-inject-loader](https://github.com/privatenumber/code-inject-loader) to accomplish this:

```
{
	loader: 'code-inject-loader',
	options: {
		transform: src => src.replace(/@license/, '')
	}
},
{
	loader: 'esbuild-loader',
	...
}
```

Note that this is risky because it doesn't guarantee that `@license` is used as a part of a comment.

**Comment by privatenumber** [comment]
Re-opening as esbuild [v0.11.15](https://github.com/evanw/esbuild/releases/tag/v0.11.15) has an option to remove comments.
