### ISSUE TITLE
Consider combining with thread-loader

### ISSUE THREAD

**Issue by NikhilVerma** [privatenumber/esbuild-loader#9]
One of the reasons esbuild is so fast is that it does parsing and transforming in parallel. But if we tie it with webpack we start using it synchronously.

If we combine this loader with thread-loader we might see much better performance -  https://webpack.js.org/loaders/thread-loader/

**Comment by remorses** [comment]
From the thread-loader docs
> Each worker is a separate node.js process, which has an overhead of ~600ms. There is also an overhead of inter-process communication.

Not sure if it would be an improvement

**Comment by bebraw** [comment]
It might be best to apply thread-loader in user space as the results aren't guaranteed due to the overhead, yeah. In the past I noticed that parallelization begins to pay off only at bigger projects and it's best to be done on a higher level (webpack-parallel etc.) but then you are looking at compiling multiple webpack configurations in parallel instead of parallelizing inside one specific build.

That's why I'm not sure if it makes sense to couple thread-loader with this loader specifically but there could be an example of the usage for sure.

**Comment by NikhilVerma** [comment]
@remorses @bebraw I understand, we ran this test on our internal styleguide (around 1000+ typescript modules) and here are the results.

```
esbuild-loader - Time: 32756ms
- combined with thread-loader without options - 27645ms
- combined with options from example - https://webpack.js.org/loaders/thread-loader/ - Time: 26911ms
swc-loader - Time: 26798ms
 - with thread-loader without options - 29400ms
 - with options from example - https://webpack.js.org/loaders/thread-loader/ - Time: Time: 27384ms
```

It's not thorough by any means but it helped us a lot!

**Comment by bebraw** [comment]
@NikhilVerma Those are interesting results.

I imagine especially with TypeScript caching can have quite an impact. Depending on your approach (styleguidist, Storybook, ...), I've learned that there's often potential in caching type parsing. To get a baseline, you could generate a build without type parsing so you know its impact. Caching then approaches that figure vs. not caching at all.

The next question is, what's the impact of webpack 4 vs. 5 as 5 supposedly has better caching behavior out of the box without having to deal with DLLs.

**Comment by privatenumber** [comment]
Seems like this is a Webpack optimization that can be used to improve any loader.

Closing since it's not specifically relevant to esbuild-loader
