### ISSUE TITLE
How to use --inject

### ISSUE THREAD

**Issue by kevinfaveri** [privatenumber/esbuild-loader#92]
There is any way to use the --inject option with this loader? https://github.com/evanw/esbuild/blob/03a33e6e007467d99989ecf82fad61bd928a71aa/CHANGELOG.md#0717

**Comment by privatenumber** [comment]
Nope. Currently, it's [only available in the esbuild "build" API](https://github.com/evanw/esbuild/blob/e220328/lib/types.ts#L53) which accesses the file-system.

esbuild-loader uses the transform API so transforms can be done in-memory.


You can try requesting that [esbuild](https://github.com/evanw/esbuild) adds this to their transform API but since the inject feature reads from the file-system, I doubt it will be supported.

Do you mind sharing your use-case?
I'm thinking [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/) or [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) might solve your problem as they do similar things.

**Comment by privatenumber** [comment]
Closing this as it's more of a help than an issue.

Feel free to follow up with the use-case if you're still tackling it.
