### ISSUE TITLE
Update ESBuild to latest version

### ISSUE THREAD

**Issue by khasky** [privatenumber/esbuild-loader#93]
Looks like the loader is using an outdated esbuild version **0.8.28** while latest is **0.8.32**.
Thanks

**Comment by privatenumber** [comment]
Updated and released in v2.8.0

**Comment by kirill-konshin** [comment]
For future, if you're using `yarn` you can add following to `package.json`:

```json
{
  "resolutions": {
    "esbuild": "0.8.33",
  }
}
```

**Comment by privatenumber** [comment]
Good point, thanks for mentioning @kirill-konshin 

Also want to add that I plan on making esbuild a peer dependency when it reaches a stable release so users can upgrade freely.

Since they can still do breaking changes (and they have), esbuild-loader must remain tightly coupled to specific esbuild versions.
